server:
  port: 8080

spring:
  application:
    name: syhthems-gateway

eureka:
  client:
    service-url:
      defaultZone: ${SYHTHEMS_EUREKA_DEFAULT_ZONE:http://eureka.syhthems.local:7000/eureka/}
  instance:
    instance-id: syhthems-gateway-8080
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info

info:
  app.name: ${spring.application.name}
  app.java.version: @java.version@
  app.java.runtime-version: @java.runtime.version@
  app.spring-boot.version: @spring-boot.version@
  app.spring-cloud.version: @spring-cloud-dependencies.version@
  build.artifactId: @project.artifactId@
  build.version: @project.version@

zuul:
  routes:
    sso:
      path: /sso/**
      serviceId: syhthems-sso
      sensitiveHeaders: none
      stripPrefix: false
    api:
      path: /api/**
      serviceId: syhthems-api
  ignored-services: "*"
  sensitiveHeaders: Cookie,Set-Cookie
  add-host-header: true

logging:
  level:
    top.sunriseydy.syhthems: debug